/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrilldownWidgetRouteImport } from './routes/drilldown.$widget'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const DrilldownWidgetRoute = DrilldownWidgetRouteImport.update({
  id: '/drilldown/$widget',
  path: '/drilldown/$widget',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drilldown/$widget': typeof DrilldownWidgetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drilldown/$widget': typeof DrilldownWidgetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drilldown/$widget': typeof DrilldownWidgetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drilldown/$widget'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drilldown/$widget'
  id: '__root__' | '/' | '/drilldown/$widget'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrilldownWidgetRoute: typeof DrilldownWidgetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drilldown/$widget': {
      id: '/drilldown/$widget'
      path: '/drilldown/$widget'
      fullPath: '/drilldown/$widget'
      preLoaderRoute: typeof DrilldownWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrilldownWidgetRoute: DrilldownWidgetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
